### PR TITLE
BindIp fixes

### PR DESCRIPTION
**Pull request by JamyDev**

### CODE REVIEW

**Comment by tips48** [comment]
Or just call config.addDefault("General.bindIP", "0.0.0.0") so it adds correctly ;)

**Comment by JamyDev** [comment]
It's nicer to see an empty field for that value, as well as all servers that have it empty right now need the correct value ;)

**Comment by tips48** [comment]
It will autoupdate if there is no value..and whatever. i just like having key: value instead of key:

**Comment by JamyDev** [comment]
problem is the value is '' <-- two single quotes, and I don't think it auto
updates then ...

2012/8/22 Aidan M. notifications@github.com

**Comment by tips48** [comment]
It should, and whatever it's not a big deal

**Pull request merged**
